# Site settings
title: ""
email: I-am-sure-you-can-figure-it-out@somewhere.com
description:
  this means to ignore newlines until "baseurl:"
  # Write an awesome description for your new site here. You can edit this
  # line in _config.yml. It will appear in your document head meta (for
  # Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://thepavolc.github.io/"
github_username: ThePavolC
linkedin_username: pavolceluch
instagram_username: pavolceluch

# Build settings
markdown: kramdown

analytics:
  provider: google
  google:
    tracking_id: "UA-61785596-1"
